export const UNFREEZE_PROGRESS_STAGES = {
  MINISTRY_REPORTING: "ministry-reporting",
  LEGISLATIVE_REVIEW: "legislative-review",
  UNFREEZE_COMPLETE: "unfreeze-complete",
} as const;

export type UnfreezeProgressStage =
  (typeof UNFREEZE_PROGRESS_STAGES)[keyof typeof UNFREEZE_PROGRESS_STAGES];

export const UNFREEZE_PROGRESS_ORDER: UnfreezeProgressStage[] = [
  UNFREEZE_PROGRESS_STAGES.MINISTRY_REPORTING,
  UNFREEZE_PROGRESS_STAGES.LEGISLATIVE_REVIEW,
  UNFREEZE_PROGRESS_STAGES.UNFREEZE_COMPLETE,
];

export const UNFREEZE_PROGRESS_LABELS: Record<UnfreezeProgressStage, string> = {
  [UNFREEZE_PROGRESS_STAGES.MINISTRY_REPORTING]: "部會開始提出解凍報告",
  [UNFREEZE_PROGRESS_STAGES.LEGISLATIVE_REVIEW]: "立法院審議中",
  [UNFREEZE_PROGRESS_STAGES.UNFREEZE_COMPLETE]: "全數解凍案解凍完畢",
};

export const UNFREEZE_PROGRESS_PERCENTAGES: Record<
  UnfreezeProgressStage,
  number
> = {
  [UNFREEZE_PROGRESS_STAGES.MINISTRY_REPORTING]: 30,
  [UNFREEZE_PROGRESS_STAGES.LEGISLATIVE_REVIEW]: 70,
  [UNFREEZE_PROGRESS_STAGES.UNFREEZE_COMPLETE]: 100,
};
